system("cd .. && npm install shelljs@0.7.0")
system("npm install -g cordova@6.4.0")
system("cordova telemetry off")

$os = "ios,android"
$jobUrl = ENV["JOB_URL"]
unless $jobUrl.nil?
	if $jobUrl.include?"Android-Package"
		$os = "android"
  elsif $jobUrl.include?"iOS-Package"
		$os = "ios"
	end
end
puts "OS is set to #$os"

$branch = ENV["branch"]
if $branch.nil?
	$branch = "dev"
end
puts "Branch is set to #$branch"

lane :all do
	system("node ../test/test_force.js --#$branch --os=#$os --apptype=native,native_swift,react_native,hybrid_remote,hybrid_local")
	system("node ../test_force.js --os=#$os --templaterepouri=https://github.com/forcedotcom/SmartSyncExplorerReactNative#master")
end

lane :native do
	system("node ../test/test_force.js --#$branch --os=#$os --apptype=native")
end

lane :native_swift do
	system("node ../test/test_force.js --#$branch --os=ios --apptype=native_swift")
end

lane :react_native do
	system("node ../test/test_force.js --#$branch --os=#$os --apptype=react_native")
	system("node ../test/test_force.js --#$branch --os=#$os --templaterepouri=https://github.com/forcedotcom/SmartSyncExplorerReactNative#master")
end

lane :hybrid do
	system("node ../test/test_force.js --#$branch --os=#$os --apptype=hybrid_remote,hybrid_local")
end
