system("npm install shelljs@0.7.0")
system("npm install -g cordova")
system("cordova telemetry on")

$os = "ios,android"
$jenkins = ENV["JENKINS_URL"]
unless $jenkins.nil?
	if $jenkins.include?"Android-Package"
		$os = "android"
  elsif $jenkins.include?"iOS-Package"
		$os = "ios"
	end
end

lane :all do
	system("set -o pipefail && node ../test/test_force.js --os=#$os --apptype=native,native_swift,react_native,hybrid_remote,hybrid_local")
	system("set -o pipefail && node test_force.js --os=#$os --templaterepouri=https://github.com/forcedotcom/SmartSyncExplorerReactNative#master")
end

lane :native do
	system("set -o pipefail && node ../test/test_force.js --os=#$os --apptype=native")
end

lane :native_swift do
	system("node ../test/test_force.js --os=ios --apptype=native_swift")
end

lane :react_native do
	system("set -o pipefail && node ../test/test_force.js --os=#$os --apptype=react_native")
	system("set -o pipefail && node ../test/test_force.js --os=#$os --templaterepouri=https://github.com/forcedotcom/SmartSyncExplorerReactNative#master")
end

lane :hybrid do
	system("set -o pipefail && node ../test/test_force.js --os=#$os --apptype=hybrid_remote,hybrid_local")
end
