name: Pull Request

on:
  pull_request:
    branches: [dev, master]

jobs:
  android-pr:
    strategy:
      fail-fast: false
    uses: ./.github/workflows/android-reusable-workflow.yaml
    with:
      is_pr: true

  ios-pr:
    strategy:
      fail-fast: false
    uses: ./.github/workflows/ios-reusable-workflow.yaml
    with:
      is_pr: true